[changelog]
header = """
# Changelog

Todas as mudanças importantes deste projeto serão documentadas neste arquivo.

"""

body = """
{% if version %}
## {{ version }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}
## Unreleased
{% endif %}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}

{% for commit in commits %}
- {{ commit.message }}
{% endfor %}
{% endfor %}
"""

footer = ""

trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
tag_pattern = "v[0-9]*"
ignore_tags = ""
topo_order = false
sort_commits = "oldest"

commit_preprocessors = []

commit_parsers = [
    { message = "^feat", group = "✨ Novidades" },
    { message = "^fix", group = "🐛 Correções" },
    { message = "^perf", group = "⚡ Desempenho" },
    { message = "^refactor", group = "♻️ Refatoração" },
    { message = "^docs", group = "📚 Documentação" },
    { message = "^style", group = "🎨 Estilo" },
    { message = "^test", group = "🧪 Testes" },
    { message = "^build", group = "🏗 Build" },
    { message = "^ci", group = "🤖 CI/CD" },
    { message = "^chore", group = "🔧 Manutenção" },
    { message = ".*", group = "Outras alterações" }
]